workflows:
  android-build:
    name: Build Android App
    environment:
      android:
        image: android-stable
      vars:
        PACKAGE_NAME: "com.kambiz.kamrobot"
    scripts:
      - ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
