workflows:
  android-build:
    name: Build Android App
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.kambiz.kamrobot"
    scripts:
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
